/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTracksRouteImport } from './routes/admin/tracks'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSellersRouteImport } from './routes/admin/sellers'
import { Route as AdminSellerTiersRouteImport } from './routes/admin/seller-tiers'
import { Route as AdminSellerApplicationsRouteImport } from './routes/admin/seller-applications'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as AdminRefundsRouteImport } from './routes/admin/refunds'
import { Route as AdminRecentlySoldRouteImport } from './routes/admin/recently-sold'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminGigsRouteImport } from './routes/admin/gigs'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSellerTiersRoute = AdminSellerTiersRouteImport.update({
  id: '/seller-tiers',
  path: '/seller-tiers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSellerApplicationsRoute = AdminSellerApplicationsRouteImport.update({
  id: '/seller-applications',
  path: '/seller-applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecentlySoldRoute = AdminRecentlySoldRouteImport.update({
  id: '/recently-sold',
  path: '/recently-sold',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGigsRoute = AdminGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recently-sold': typeof AdminRecentlySoldRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seller-applications': typeof AdminSellerApplicationsRoute
  '/admin/seller-tiers': typeof AdminSellerTiersRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recently-sold': typeof AdminRecentlySoldRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seller-applications': typeof AdminSellerApplicationsRoute
  '/admin/seller-tiers': typeof AdminSellerTiersRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/gigs': typeof AdminGigsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/recently-sold': typeof AdminRecentlySoldRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/seller-applications': typeof AdminSellerApplicationsRoute
  '/admin/seller-tiers': typeof AdminSellerTiersRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/feature-flags'
    | '/admin/gigs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/recently-sold'
    | '/admin/refunds'
    | '/admin/search'
    | '/admin/seller-applications'
    | '/admin/seller-tiers'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/feature-flags'
    | '/admin/gigs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/recently-sold'
    | '/admin/refunds'
    | '/admin/search'
    | '/admin/seller-applications'
    | '/admin/seller-tiers'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/feature-flags'
    | '/admin/gigs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/recently-sold'
    | '/admin/refunds'
    | '/admin/search'
    | '/admin/seller-applications'
    | '/admin/seller-tiers'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seller-tiers': {
      id: '/admin/seller-tiers'
      path: '/seller-tiers'
      fullPath: '/admin/seller-tiers'
      preLoaderRoute: typeof AdminSellerTiersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seller-applications': {
      id: '/admin/seller-applications'
      path: '/seller-applications'
      fullPath: '/admin/seller-applications'
      preLoaderRoute: typeof AdminSellerApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/recently-sold': {
      id: '/admin/recently-sold'
      path: '/recently-sold'
      fullPath: '/admin/recently-sold'
      preLoaderRoute: typeof AdminRecentlySoldRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gigs': {
      id: '/admin/gigs'
      path: '/gigs'
      fullPath: '/admin/gigs'
      preLoaderRoute: typeof AdminGigsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminGigsRoute: typeof AdminGigsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRecentlySoldRoute: typeof AdminRecentlySoldRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSellerApplicationsRoute: typeof AdminSellerApplicationsRoute
  AdminSellerTiersRoute: typeof AdminSellerTiersRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminGigsRoute: AdminGigsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRecentlySoldRoute: AdminRecentlySoldRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSellerApplicationsRoute: AdminSellerApplicationsRoute,
  AdminSellerTiersRoute: AdminSellerTiersRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
