/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsGhostProductionRouteImport } from './routes/what-is-ghost-production'
import { Route as WhatIsGhostProducerRouteImport } from './routes/what-is-ghost-producer'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SellerAgreementRouteImport } from './routes/seller-agreement'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicensingLegalRouteImport } from './routes/licensing-legal'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as HowToUploadTracksRouteImport } from './routes/how-to-upload-tracks'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplySellerRouteImport } from './routes/apply-seller'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as SellersUsernameRouteImport } from './routes/sellers.$username'
import { Route as GenresSlugRouteImport } from './routes/genres.$slug'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardTracksRouteImport } from './routes/dashboard.tracks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardKycRouteImport } from './routes/dashboard.kyc'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountMailingRouteImport } from './routes/account.mailing'
import { Route as AccountFollowingRouteImport } from './routes/account.following'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'

const WhatIsGhostProductionRoute = WhatIsGhostProductionRouteImport.update({
  id: '/what-is-ghost-production',
  path: '/what-is-ghost-production',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsGhostProducerRoute = WhatIsGhostProducerRouteImport.update({
  id: '/what-is-ghost-producer',
  path: '/what-is-ghost-producer',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAgreementRoute = SellerAgreementRouteImport.update({
  id: '/seller-agreement',
  path: '/seller-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingLegalRoute = LicensingLegalRouteImport.update({
  id: '/licensing-legal',
  path: '/licensing-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUploadTracksRoute = HowToUploadTracksRouteImport.update({
  id: '/how-to-upload-tracks',
  path: '/how-to-upload-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySellerRoute = ApplySellerRouteImport.update({
  id: '/apply-seller',
  path: '/apply-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TracksRoute,
} as any)
const SellersUsernameRoute = SellersUsernameRouteImport.update({
  id: '/sellers/$username',
  path: '/sellers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresSlugRoute = GenresSlugRouteImport.update({
  id: '/genres/$slug',
  path: '/genres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksRoute = DashboardTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMailingRoute = AccountMailingRouteImport.update({
  id: '/mailing',
  path: '/mailing',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFollowingRoute = AccountFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/apply-seller': typeof ApplySellerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-upload-tracks': typeof HowToUploadTracksRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/licensing-legal': typeof LicensingLegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sell': typeof SellRoute
  '/seller-agreement': typeof SellerAgreementRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRouteWithChildren
  '/what-is-ghost-producer': typeof WhatIsGhostProducerRoute
  '/what-is-ghost-production': typeof WhatIsGhostProductionRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/sellers/$username': typeof SellersUsernameRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-seller': typeof ApplySellerRoute
  '/contact': typeof ContactRoute
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-upload-tracks': typeof HowToUploadTracksRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/licensing-legal': typeof LicensingLegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sell': typeof SellRoute
  '/seller-agreement': typeof SellerAgreementRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRouteWithChildren
  '/what-is-ghost-producer': typeof WhatIsGhostProducerRoute
  '/what-is-ghost-production': typeof WhatIsGhostProductionRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/sellers/$username': typeof SellersUsernameRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account': typeof AccountIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/apply-seller': typeof ApplySellerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dmca': typeof DmcaRoute
  '/faq': typeof FaqRoute
  '/how-to-upload-tracks': typeof HowToUploadTracksRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/licensing-legal': typeof LicensingLegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sell': typeof SellRoute
  '/seller-agreement': typeof SellerAgreementRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRouteWithChildren
  '/what-is-ghost-producer': typeof WhatIsGhostProducerRoute
  '/what-is-ghost-production': typeof WhatIsGhostProductionRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/support': typeof AccountSupportRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/sellers/$username': typeof SellersUsernameRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/apply-seller'
    | '/contact'
    | '/dashboard'
    | '/dmca'
    | '/faq'
    | '/how-to-upload-tracks'
    | '/how-we-work'
    | '/legal'
    | '/licensing-legal'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/sell'
    | '/seller-agreement'
    | '/terms'
    | '/tracks'
    | '/what-is-ghost-producer'
    | '/what-is-ghost-production'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/account/support'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/genres/$slug'
    | '/sellers/$username'
    | '/tracks/$id'
    | '/account/'
    | '/blog/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-seller'
    | '/contact'
    | '/dmca'
    | '/faq'
    | '/how-to-upload-tracks'
    | '/how-we-work'
    | '/legal'
    | '/licensing-legal'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/sell'
    | '/seller-agreement'
    | '/terms'
    | '/tracks'
    | '/what-is-ghost-producer'
    | '/what-is-ghost-production'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/account/support'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/genres/$slug'
    | '/sellers/$username'
    | '/tracks/$id'
    | '/account'
    | '/blog'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/apply-seller'
    | '/contact'
    | '/dashboard'
    | '/dmca'
    | '/faq'
    | '/how-to-upload-tracks'
    | '/how-we-work'
    | '/legal'
    | '/licensing-legal'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/sell'
    | '/seller-agreement'
    | '/terms'
    | '/tracks'
    | '/what-is-ghost-producer'
    | '/what-is-ghost-production'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/account/support'
    | '/blog/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/genres/$slug'
    | '/sellers/$username'
    | '/tracks/$id'
    | '/account/'
    | '/blog/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ApplySellerRoute: typeof ApplySellerRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DmcaRoute: typeof DmcaRoute
  FaqRoute: typeof FaqRoute
  HowToUploadTracksRoute: typeof HowToUploadTracksRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  LegalRoute: typeof LegalRoute
  LicensingLegalRoute: typeof LicensingLegalRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SellRoute: typeof SellRoute
  SellerAgreementRoute: typeof SellerAgreementRoute
  TermsRoute: typeof TermsRoute
  TracksRoute: typeof TracksRouteWithChildren
  WhatIsGhostProducerRoute: typeof WhatIsGhostProducerRoute
  WhatIsGhostProductionRoute: typeof WhatIsGhostProductionRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GenresSlugRoute: typeof GenresSlugRoute
  SellersUsernameRoute: typeof SellersUsernameRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-ghost-production': {
      id: '/what-is-ghost-production'
      path: '/what-is-ghost-production'
      fullPath: '/what-is-ghost-production'
      preLoaderRoute: typeof WhatIsGhostProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-ghost-producer': {
      id: '/what-is-ghost-producer'
      path: '/what-is-ghost-producer'
      fullPath: '/what-is-ghost-producer'
      preLoaderRoute: typeof WhatIsGhostProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-agreement': {
      id: '/seller-agreement'
      path: '/seller-agreement'
      fullPath: '/seller-agreement'
      preLoaderRoute: typeof SellerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing-legal': {
      id: '/licensing-legal'
      path: '/licensing-legal'
      fullPath: '/licensing-legal'
      preLoaderRoute: typeof LicensingLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-upload-tracks': {
      id: '/how-to-upload-tracks'
      path: '/how-to-upload-tracks'
      fullPath: '/how-to-upload-tracks'
      preLoaderRoute: typeof HowToUploadTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-seller': {
      id: '/apply-seller'
      path: '/apply-seller'
      fullPath: '/apply-seller'
      preLoaderRoute: typeof ApplySellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof TracksRoute
    }
    '/sellers/$username': {
      id: '/sellers/$username'
      path: '/sellers/$username'
      fullPath: '/sellers/$username'
      preLoaderRoute: typeof SellersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$slug': {
      id: '/genres/$slug'
      path: '/genres/$slug'
      fullPath: '/genres/$slug'
      preLoaderRoute: typeof GenresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks': {
      id: '/dashboard/tracks'
      path: '/tracks'
      fullPath: '/dashboard/tracks'
      preLoaderRoute: typeof DashboardTracksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kyc': {
      id: '/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/mailing': {
      id: '/account/mailing'
      path: '/mailing'
      fullPath: '/account/mailing'
      preLoaderRoute: typeof AccountMailingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/following': {
      id: '/account/following'
      path: '/following'
      fullPath: '/account/following'
      preLoaderRoute: typeof AccountFollowingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountFollowingRoute: typeof AccountFollowingRoute
  AccountMailingRoute: typeof AccountMailingRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountFollowingRoute: AccountFollowingRoute,
  AccountMailingRoute: AccountMailingRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardKycRoute: typeof DashboardKycRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTracksRoute: typeof DashboardTracksRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardKycRoute: DashboardKycRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTracksRoute: DashboardTracksRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TracksRouteChildren {
  TracksIdRoute: typeof TracksIdRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksIdRoute: TracksIdRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ApplySellerRoute: ApplySellerRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DmcaRoute: DmcaRoute,
  FaqRoute: FaqRoute,
  HowToUploadTracksRoute: HowToUploadTracksRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  LegalRoute: LegalRoute,
  LicensingLegalRoute: LicensingLegalRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SellRoute: SellRoute,
  SellerAgreementRoute: SellerAgreementRoute,
  TermsRoute: TermsRoute,
  TracksRoute: TracksRouteWithChildren,
  WhatIsGhostProducerRoute: WhatIsGhostProducerRoute,
  WhatIsGhostProductionRoute: WhatIsGhostProductionRoute,
  BlogSlugRoute: BlogSlugRoute,
  GenresSlugRoute: GenresSlugRoute,
  SellersUsernameRoute: SellersUsernameRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
