/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellRouteImport } from './routes/sell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplySellerRouteImport } from './routes/apply-seller'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardTracksRouteImport } from './routes/dashboard.tracks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardKycRouteImport } from './routes/dashboard.kyc'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTracksRouteImport } from './routes/admin.tracks'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountMailingRouteImport } from './routes/account.mailing'
import { Route as AccountFollowingRouteImport } from './routes/account.following'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySellerRoute = ApplySellerRouteImport.update({
  id: '/apply-seller',
  path: '/apply-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TracksRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksRoute = DashboardTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMailingRoute = AccountMailingRouteImport.update({
  id: '/mailing',
  path: '/mailing',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFollowingRoute = AccountFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/apply-seller': typeof ApplySellerRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/tracks': typeof TracksRouteWithChildren
  '/upload': typeof UploadRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-seller': typeof ApplySellerRoute
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/tracks': typeof TracksRouteWithChildren
  '/upload': typeof UploadRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/apply-seller': typeof ApplySellerRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/tracks': typeof TracksRouteWithChildren
  '/upload': typeof UploadRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/mailing': typeof AccountMailingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracks': typeof DashboardTracksRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/tracks/$id': typeof TracksIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/apply-seller'
    | '/dashboard'
    | '/faq'
    | '/how-we-work'
    | '/legal'
    | '/login'
    | '/sell'
    | '/services'
    | '/tracks'
    | '/upload'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/tracks'
    | '/admin/users'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/tracks/$id'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-seller'
    | '/faq'
    | '/how-we-work'
    | '/legal'
    | '/login'
    | '/sell'
    | '/services'
    | '/tracks'
    | '/upload'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/tracks'
    | '/admin/users'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/tracks/$id'
    | '/account'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/apply-seller'
    | '/dashboard'
    | '/faq'
    | '/how-we-work'
    | '/legal'
    | '/login'
    | '/sell'
    | '/services'
    | '/tracks'
    | '/upload'
    | '/account/favorites'
    | '/account/following'
    | '/account/mailing'
    | '/account/orders'
    | '/account/profile'
    | '/admin/kyc'
    | '/admin/orders'
    | '/admin/tracks'
    | '/admin/users'
    | '/checkout/success'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/kyc'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tracks'
    | '/dashboard/upload'
    | '/tracks/$id'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApplySellerRoute: typeof ApplySellerRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  ServicesRoute: typeof ServicesRoute
  TracksRoute: typeof TracksRouteWithChildren
  UploadRoute: typeof UploadRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-seller': {
      id: '/apply-seller'
      path: '/apply-seller'
      fullPath: '/apply-seller'
      preLoaderRoute: typeof ApplySellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof TracksRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks': {
      id: '/dashboard/tracks'
      path: '/tracks'
      fullPath: '/dashboard/tracks'
      preLoaderRoute: typeof DashboardTracksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kyc': {
      id: '/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/mailing': {
      id: '/account/mailing'
      path: '/mailing'
      fullPath: '/account/mailing'
      preLoaderRoute: typeof AccountMailingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/following': {
      id: '/account/following'
      path: '/following'
      fullPath: '/account/following'
      preLoaderRoute: typeof AccountFollowingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountFollowingRoute: typeof AccountFollowingRoute
  AccountMailingRoute: typeof AccountMailingRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountFollowingRoute: AccountFollowingRoute,
  AccountMailingRoute: AccountMailingRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminKycRoute: typeof AdminKycRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKycRoute: AdminKycRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardKycRoute: typeof DashboardKycRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTracksRoute: typeof DashboardTracksRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardKycRoute: DashboardKycRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTracksRoute: DashboardTracksRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TracksRouteChildren {
  TracksIdRoute: typeof TracksIdRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksIdRoute: TracksIdRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApplySellerRoute: ApplySellerRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  ServicesRoute: ServicesRoute,
  TracksRoute: TracksRouteWithChildren,
  UploadRoute: UploadRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
